Try to Fix Travis node_js version to 4.7.0
ERROR: npm is known not to run on Node.js v4.2.0
Node.js 4 is supported but the specific version you're running has
a bug known to break npm. Please update to at least 4.7.0 to use this
version of npm. You can find the latest release of Node.js at https://nodejs.org/